name: ecrivai
dependencies:
  - python=3.10
  - pip
  - pip:
    - jupyterlab==3.4.8
    - langchain==0.0.153
    - openai==0.27.6
    - python-dotenv==1.0.0
    - black==23.3.0
    - pylint==2.17.4
    - -e .
